name = "gpt-park-blog"
compatibility_date = "2024-04-01"

[[d1_databases]]
binding = "DB"
database_name = "gpt-park-db"
database_id = "92276bb0-0517-4135-b9ab-823e398419bf" # User needs to replace this after creation

[site]
bucket = "./public"
entry-point = "workers-site"
